In [1]:
%load_ext pycodestyle_magic
%load_ext mypy_ipython
%pycodestyle_on

In [2]:
import doctest

In [3]:
import numpy as np
import numpy.linalg as la

"""

>>> m = np.matrix([[1, -2, 3], [0, 4, 5], [7, 8, -9]])
>>> m
matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])
>>> m.T
matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])
>>> m.I
matrix([[ 0.33043478, -0.02608696,  0.09565217],
        [-0.15217391,  0.13043478,  0.02173913],
        [ 0.12173913,  0.09565217, -0.0173913 ]])
>>> v = np.matrix([[2], [3], [4]])
>>> v
matrix([[2],
        [3],
        [4]])
>>> m * v
matrix([[ 8],
        [32],
        [ 2]])
>>> la.det(m)
-229.99999999999983
>>> la.eigvals(m)
array([-13.11474312,   2.75956154,   6.35518158])
>>> x = la.solve(m, v)
>>> x
matrix([[0.96521739],
        [0.17391304],
        [0.46086957]])
>>> m * x
matrix([[2.],
        [3.],
        [4.]])
>>> v
matrix([[2],
        [3],
        [4]])
"""

doctest.testmod()

TestResults(failed=0, attempted=13)