In [1]:
%load_ext pycodestyle_magic
%load_ext mypy_ipython
%pycodestyle_on

In [2]:
import doctest

In [3]:
import cmath

"""

>>> a = complex(2, 4)
>>> b = 3 - 5j
>>> a
(2+4j)
>>> b
(3-5j)
>>> a.real, a.imag
(2.0, 4.0)
>>> a.conjugate()
(2-4j)
>>> a + b
(5-1j)
>>> a * b
(26+2j)
>>> a / b
(-0.4117647058823529+0.6470588235294118j)
>>> abs(a)
4.47213595499958
>>> cmath.sin(a)
(24.83130584894638-11.356612711218173j)
>>> cmath.cos(a)
(-11.36423470640106-24.814651485634183j)
>>> cmath.exp(a)
(-4.829809383269385-5.5920560936409816j)
"""

doctest.testmod()

TestResults(failed=0, attempted=13)

In [4]:
import numpy as np

"""

>>> a = np.array([2+3j, 4+5j, 6-7j, 8+9j])
>>> a
array([2.+3.j, 4.+5.j, 6.-7.j, 8.+9.j])
>>> a + 2
array([ 4.+3.j,  6.+5.j,  8.-7.j, 10.+9.j])
>>> np.sin(a)
array([   9.15449915  -4.16890696j,  -56.16227422 -48.50245524j,
       -153.20827755-526.47684926j, 4008.42651446-589.49948373j])
"""

doctest.testmod()

TestResults(failed=0, attempted=4)

In [5]:
import math
import cmath

"""

>>> math.sqrt(-1)
Traceback (most recent call last):
    ...
ValueError: math domain error
>>> cmath.sqrt(-1)
1j
"""

doctest.testmod()

TestResults(failed=0, attempted=2)